name: everglow_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Navigation
  go_router: ^14.6.2

  # Networking
  dio: ^5.7.0
  json_annotation: ^4.9.0

  # Audio
  just_audio: ^0.9.42
  audio_session: ^0.1.21

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # PDF Export
  pdf: ^3.11.1
  printing: ^5.13.4
  riverpod_annotation: ^2.6.1
  retrofit: ^4.7.3

  # Markdown Rendering
  flutter_markdown: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.2.1
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#000000"  # Black background
  android: true
  ios: true
  web: false

  # Android 12+ specific settings
  android_12:
    color: "#000000"  # Black background for Android 12+
