import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

part 'ai_report_service.g.dart';

/// Retrofit service interface for communicating with Google AI (Gemini) API.
///
/// This abstract class defines the contract for communicating with the Gemini API
/// using Retrofit annotations. The implementation is generated by retrofit_generator.
///
/// The service communicates with Google's Generative Language API to generate
/// content using the Gemini 2.5 Flash Lite model.
///
/// Usage example:
/// ```dart
/// final dio = Dio(BaseOptions(baseUrl: 'https://generativelanguage.googleapis.com'));
/// final service = AiReportService(dio);
/// final response = await service.generateReport({
///   'contents': [
///     {
///       'parts': [
///         {'text': 'Your prompt here'}
///       ]
///     }
///   ]
/// });
/// ```
@RestApi(baseUrl: 'https://generativelanguage.googleapis.com')
abstract class AiReportService {
  /// Factory constructor that creates an instance using the generated implementation.
  ///
  /// [dio] The Dio instance to use for HTTP requests.
  /// [baseUrl] Optional base URL override. If not provided, uses the RestApi baseUrl.
  factory AiReportService(Dio dio, {String baseUrl}) = _AiReportService;

  /// Generates content using the Gemini 2.5 Flash Lite model.
  ///
  /// Sends a POST request to the Gemini API to generate content based on the
  /// provided request body.
  ///
  /// [requestBody] A map containing the request configuration including:
  /// - 'contents': List of content parts with text prompts
  /// - 'generationConfig': Optional generation configuration
  /// - 'safetySettings': Optional safety settings
  ///
  /// Returns a map containing the full API response including:
  /// - 'candidates': List of generated content candidates
  /// - 'promptFeedback': Feedback about the prompt
  /// - 'usageMetadata': Token usage information
  ///
  /// Throws [DioException] if the request fails.
  ///
  /// Example request body:
  /// ```dart
  /// {
  ///   'contents': [
  ///     {
  ///       'parts': [
  ///         {'text': 'Write a story about a magic backpack'}
  ///       ]
  ///     }
  ///   ]
  /// }
  /// ```
  @POST('/v1beta/models/gemini-2.5-flash-lite:generateContent')
  Future<HttpResponse<dynamic>> generateReport(
    @Body() Map<String, dynamic> requestBody,
  );
}
